/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js,ts}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // ── SewaKen Design Tokens (exact dari Stitch) ──
        'primary':                  '#000000',
        'on-primary':               '#ffffff',
        'primary-container':        '#131b2e',
        'on-primary-container':     '#7c839b',
        'primary-fixed':            '#dae2fd',
        'primary-fixed-dim':        '#bec6e0',
        'on-primary-fixed':         '#131b2e',
        'on-primary-fixed-variant': '#3f465c',
        'inverse-primary':          '#bec6e0',

        'secondary':                '#0058be',
        'on-secondary':             '#ffffff',
        'secondary-container':      '#2170e4',
        'on-secondary-container':   '#fefcff',
        'secondary-fixed':          '#d8e2ff',
        'secondary-fixed-dim':      '#adc6ff',
        'on-secondary-fixed':       '#001a42',
        'on-secondary-fixed-variant':'#004395',

        'tertiary':                 '#000000',
        'on-tertiary':              '#ffffff',
        'tertiary-container':       '#271901',
        'on-tertiary-container':    '#98805d',
        'tertiary-fixed':           '#fcdeb5',
        'tertiary-fixed-dim':       '#dec29a',
        'on-tertiary-fixed':        '#271901',
        'on-tertiary-fixed-variant':'#574425',

        'error':                    '#ba1a1a',
        'on-error':                 '#ffffff',
        'error-container':          '#ffdad6',
        'on-error-container':       '#93000a',

        'background':               '#fcf8fa',
        'on-background':            '#1b1b1d',
        'surface':                  '#fcf8fa',
        'surface-bright':           '#fcf8fa',
        'surface-dim':              '#dcd9db',
        'surface-tint':             '#565e74',
        'on-surface':               '#1b1b1d',
        'on-surface-variant':       '#45464d',
        'surface-variant':          '#e4e2e4',
        'surface-container-lowest': '#ffffff',
        'surface-container-low':    '#f6f3f5',
        'surface-container':        '#f0edef',
        'surface-container-high':   '#eae7e9',
        'surface-container-highest':'#e4e2e4',
        'inverse-surface':          '#303032',
        'inverse-on-surface':       '#f3f0f2',

        'outline':                  '#76777d',
        'outline-variant':          '#c6c6cd',
        'surface-tint':             '#565e74',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        '2xl':   '1rem',
        full:    '9999px',
      },
      spacing: {
        'base':            '4px',
        'gutter':          '24px',
        'margin-mobile':   '16px',
        'margin-desktop':  '32px',
        'section-gap':     '80px',
        'container-max':   '1280px',
      },
      fontFamily: {
        'headline-lg':       ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md':       ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg-mobile':['Plus Jakarta Sans', 'sans-serif'],
        'display-lg':        ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg':           ['Inter', 'sans-serif'],
        'body-md':           ['Inter', 'sans-serif'],
        'label-md':          ['Inter', 'sans-serif'],
        'label-sm':          ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg':        ['48px', { lineHeight:'1.2', letterSpacing:'-0.02em', fontWeight:'700' }],
        'headline-lg':       ['32px', { lineHeight:'1.3', fontWeight:'700' }],
        'headline-lg-mobile':['24px', { lineHeight:'1.3', fontWeight:'700' }],
        'headline-md':       ['24px', { lineHeight:'1.4', fontWeight:'600' }],
        'body-lg':           ['18px', { lineHeight:'1.6', fontWeight:'400' }],
        'body-md':           ['16px', { lineHeight:'1.6', fontWeight:'400' }],
        'label-md':          ['14px', { lineHeight:'1.2', fontWeight:'500' }],
        'label-sm':          ['12px', { lineHeight:'1.2', fontWeight:'600' }],
      },
    },
  },
  plugins: [],
}
